refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  main:
    kind: file
    path: "log/owl.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
    - main
loggers:
  app::backend::db:
    level: info
  app::main:
    level: info
    appenders:
      - main
    additive: false